# Copyright (C) 2026. Huawei Technologies Co., Ltd. All rights reserved.
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the MIT license.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the MIT License for more details.
#
# The name of Huawei and the contributors may not be used to endorse or promote
# products derived from this software without specific prior written permission.

import contextvars
import httpx
import asyncio
from dataclasses import dataclass, field
from pydantic import BaseModel, ConfigDict, Field, model_validator
from abc import ABC, abstractmethod
from typing import Any, List, Optional, Union, Dict, Tuple

from ..message import Message, ROLE_VALUES
from ..tool import TOOL_CHOICE_TYPE
from ..tracker.token_usage import TokenUsageTracker


@dataclass
class GuardStreamChunk:
    """Stream text consumed by guards but hidden from user-facing output and logs."""

    text: str
    channel: str


@dataclass
class StreamHandle:
    """Per-call streaming control — owns the chunk queue and interrupt signal.

    Each concurrent ``ask()`` call receives its own ``StreamHandle``, so
    interrupt / queue operations never interfere across calls even when
    they share the same LLM instance.
    """
    queue: asyncio.Queue = field(default_factory=asyncio.Queue)
    _event: asyncio.Event = field(default_factory=asyncio.Event)
    _eos_sent: bool = field(default=False, repr=False)

    @property
    def interrupted(self) -> bool:
        return self._event.is_set()

    def interrupt(self) -> None:
        """Signal the stream to stop.  Idempotent, sync-safe (``put_nowait``)."""
        if self._event.is_set():
            return
        self._event.set()
        while not self.queue.empty():
            try:
                self.queue.get_nowait()
            except asyncio.QueueEmpty:
                break
        if not self._eos_sent:
            self._eos_sent = True
            self.queue.put_nowait(None)

    def stop(self) -> None:
        """Signal stop: block further ``put`` and enqueue EOS, but keep pending chunks.

        Use after streaming the first complete tool call so the consumer can still
        print queued previews (``→ tool`` / JSON fragments).  Unlike ``interrupt()``,
        does **not** drain the queue.  Idempotent.
        """
        if self._event.is_set():
            return
        self._event.set()
        if not self._eos_sent:
            self._eos_sent = True
            self.queue.put_nowait(None)

    async def put(self, chunk: str | None) -> None:
        """Enqueue a chunk.  No-op after ``interrupt`` / ``stop`` to prevent late writes."""
        if not self._event.is_set():
            await self.queue.put(chunk)

    async def put_guard(self, chunk: str, *, channel: str) -> None:
        """Enqueue hidden text for stream guards without rendering or logging it."""
        if chunk and not self._event.is_set():
            await self.queue.put(GuardStreamChunk(text=chunk, channel=channel))

    def finish(self) -> None:
        """Signal normal end-of-stream.  Idempotent (at most one EOS sentinel)."""
        if self._eos_sent:
            return
        self._eos_sent = True
        if not self._event.is_set():
            self.queue.put_nowait(None)


@dataclass
class CallStats:
    """Per-call LLM statistics, stored in ContextVar for concurrency safety."""
    input_tokens: int = 0
    output_tokens: int = 0
    ttft: float = 0.0
    tpot: float = 0.0
    finish_reason: str = "unknown"
    # Tokens served from provider-side prompt prefix cache (real value reported by API).
    input_cached_tokens: int = 0


_call_stats_store: contextvars.ContextVar[dict[int, CallStats]] = contextvars.ContextVar(
    "_call_stats_store",
)

# class LLMResponse(BaseModel):
#     """Complete data structure wrapping a language model response.""""
#     # Core information: the generated text answer
#     answer: str = Field(description="The final text answer generated by the language model.")
#
#     # Metadata: usually included in the LLM API response
#     # Token probabilities: a dict of tokens and their probabilities, typically for advanced analysis
#     logprobs: Optional[Dict[str, float]] = Field(
#         None, description="Each generated token and its log probability (Log probabilities)."
#     )

class BaseLLM(BaseModel, ABC):
    '''
        base class for language model.
    model : The name of the language model to use for text completion.
    api_key : API key (default is None).
    base_url : The base URL for API requests.
    max_tokens : The maximum number of tokens in the generated completion.
    api_version : API version (default is None)
    temperature : The temperature parameter for controlling the randomness of the output .
    top_p : The top-p parameter for controlling the diversity of the output.
    headers : Additional headers to include in API requests.
    stream : Whether to stream the output or not. (default is True)
    tracker : Whether to track the usage of tokens or not. (default is False)
    '''
    model: Optional[str] = Field(default=None, description="model")
    api_type: Optional[str] = Field(default=None, description="api_type")
    api_key: Optional[str] = Field(default=None, description="api_key")
    base_url: Optional[str] = Field(default=None, description="base_url")
    max_tokens: Optional[int] = Field(default=4096, description="max_tokens")
    api_version: Optional[str] = Field(default=None, description="api_version")
    temperature: Optional[float] = Field(default=0.0, description="temperature")
    top_p: Optional[float] = Field(default=0.001, description="top_p")
    frequency_penalty: Optional[float] = Field(
        default=None,
        description="Penalty for repeated tokens (OpenAI-compatible APIs).",
    )
    headers: Optional[dict] = Field(default={}, description="headers")
    stream: Optional[bool] = Field(default=True, description="stream")
    tracker: Optional[bool] = Field(default=False, description="tracker")
    interrupted: Optional[bool] = Field(default=False, description="interrupted")
    reasoning_effort: Optional[str] = Field(
        default=None,
        description="Thinking budget for reasoning models (Gemini: minimal/low/medium/high). "
                    "Only sent to Gemini models; ignored for others."
    )
    chinese_token_ratio: float = Field(
        default=0.6, description="Avg number of tokens per Chinese Charactor, from https://api-docs.deepseek.com/quick_start/token_usage")
    english_token_ratio: float = Field(
        default=0.3, description="Avg number of tokens per English Charactor, from https://api-docs.deepseek.com/quick_start/token_usage")
    symbol_token_ratio: float = Field(
        default=1.0, description="Fallback: tokens per symbol when not using tiktoken. Use 0.33 for better heuristic (symbols often merge).")
    use_tiktoken_for_estimation: bool = Field(
        default=True, description="Use tiktoken for token count when model/encoding is set (accurate for OpenAI-compatible APIs).")
    tiktoken_encoding: Optional[str] = Field(
        default=None, description="tiktoken encoding name (e.g. cl100k_base). Overrides model when set.")
    # Configure a custom httpx client.
    # We provide a `DefaultHttpxClient` class that you can pass to retain the default values we use for `limits`, `timeout` & `follow_redirects`.
    # See the [httpx documentation](https://www.python-httpx.org/api/#client) for more details.
    http_asyncclient: Optional[httpx.AsyncClient] = Field(default=None, description="httpx asyncclient")
    usage_tracker: Optional[TokenUsageTracker] = Field(default_factory=TokenUsageTracker, description="Token Usage Tracker")
    chunk_queue: asyncio.Queue = Field(default_factory=asyncio.Queue, exclude=True, description="chunk queue")

    model_config = ConfigDict(arbitrary_types_allowed=True)

    @model_validator(mode="after")
    def initialize(self) -> "BaseLLM":
        self.usage_tracker = TokenUsageTracker()
        self.chunk_queue = asyncio.Queue()
        return self

    # ------------------------------------------------------------------
    # Per-call stats (ContextVar-backed, concurrency-safe)
    # ------------------------------------------------------------------

    def _save_call_stats(self, stats: CallStats) -> None:
        try:
            store = _call_stats_store.get()
        except LookupError:
            store = {}
            _call_stats_store.set(store)
        store[id(self)] = stats

    def _get_call_stats(self) -> CallStats:
        try:
            return _call_stats_store.get().get(id(self), CallStats())
        except LookupError:
            return CallStats()

    @property
    def _last_call_input_tokens(self) -> int:
        return self._get_call_stats().input_tokens

    @property
    def _last_call_output_tokens(self) -> int:
        return self._get_call_stats().output_tokens

    @property
    def _last_call_ttft(self) -> float:
        return self._get_call_stats().ttft

    @property
    def _last_call_tpot(self) -> float:
        return self._get_call_stats().tpot

    @property
    def _last_call_input_cached_tokens(self) -> int:
        return self._get_call_stats().input_cached_tokens

    @property
    def _last_finish_reason(self) -> str:
        return self._get_call_stats().finish_reason

    def estimate_tokens(self, text: str) -> int:
        """
        Estimate token count for text. Uses tiktoken when available and configured,
        otherwise falls back to character-ratio heuristic (chinese/english/symbol).
        """
        from .utils import estimate_tokens as _estimate_tokens
        return _estimate_tokens(
            text,
            model=self.model,
            encoding_name=self.tiktoken_encoding,
            use_tiktoken=self.use_tiktoken_for_estimation,
            fallback_chinese_ratio=self.chinese_token_ratio,
            fallback_english_ratio=self.english_token_ratio,
            fallback_symbol_ratio=self.symbol_token_ratio,
        )

    @staticmethod
    def format_messages(messages: List[Union[dict, Message]]) -> List[dict]:
        """
        Format messages for LLM by converting them to OpenAI message format.

        Args:
            messages: List of messages that can be either dict or Message objects

        Returns:
            List[dict]: List of formatted messages in OpenAI format

        Raises:
            ValueError: If messages are invalid or missing required fields
            TypeError: If unsupported message types are provided

        Examples:
            >>> msgs = [
            ...     Message.system_message("You are a helpful assistant"),
            ...     {"role": "user", "content": "Hello"},
            ...     Message.user_message("How are you?")
            ... ]
            >>> formatted = LLM.format_messages(msgs)
        """
        formatted_messages = []

        for message in messages:
            if isinstance(message, Message):
                message = message.to_dict()

            if isinstance(message, dict):
                # If message is a dict, ensure it has required fields
                if "role" not in message:
                    raise ValueError("Message dict must contain 'role' field")

                if (
                    "content" in message
                    or "tool_calls" in message
                    or message.get("reasoning_content") is not None
                ):
                    formatted_messages.append(message)

                # else: do not include the message
            else:
                raise TypeError(f"Unsupported message type: {type(message)}")

        # Validate all messages have required fields
        for msg in formatted_messages:
            if msg["role"] not in ROLE_VALUES:
                raise ValueError(f"Invalid role: {msg['role']}")

        return formatted_messages

    @abstractmethod
    async def ask(
        self,
        messages: List[Union[dict, Message]],
        system_msgs: Optional[List[Union[dict, Message]]] = None,
        stream: bool = True,
        temperature: Optional[float] = None,
        **kwargs,
    ) -> str: ...
    # ) -> LLMResponse: ...

    """
    Sends messages to the language model and retrieves a response.

    Args:
        messages : A list of user or system messages, which can be dictionaries or Message objects.
        system_msgs: System messages providing context or guidance.
        stream : Whether to return the response in a streaming manner. Defaults to True.
        temperature : Controls the randomness of the model's output. Defaults to None.
        **kwargs: Additional optional parameters.

    Returns:
        str: The response from the model.
    """

    @abstractmethod
    async def ask_logits(
            self,
            messages: List[Union[dict, Message]],
            system_msgs: Optional[List[Union[dict, Message]]] = None,
            stream: bool = True,
            temperature: Optional[float] = None,
            **kwargs,
    ) -> Tuple[str, Dict[str, float]]: ...

    """
    Sends messages to the language model and retrieves a response.

    Args:
        messages : A list of user or system messages, which can be dictionaries or Message objects.
        system_msgs: System messages providing context or guidance.
        stream : Whether to return the response in a streaming manner. Defaults to True.
        temperature : Controls the randomness of the model's output. Defaults to None.
        **kwargs: Additional optional parameters.

    Returns:
        str: The response from the model.
    """

    @abstractmethod
    async def ask_logits(
        self,
        messages: List[Union[dict, Message]],
        system_msgs: Optional[List[Union[dict, Message]]] = None,
        stream: bool = True,
        temperature: Optional[float] = None,
        **kwargs,
    ) -> Tuple[str, Dict[str, float]]: ...

    """
    Sends messages to the language model and retrieves a response with top 5 logprobs.

    Args:
        messages : A list of user or system messages, which can be dictionaries or Message objects.
        system_msgs: System messages providing context or guidance.
        stream : Whether to return the response in a streaming manner. Defaults to True.
        temperature : Controls the randomness of the model's output. Defaults to None.
        **kwargs: Additional optional parameters.

    Returns:
        str: The response from the model.
    """

    @abstractmethod
    async def ask_vllm_logits(
        self,
        messages: List[Union[dict, Message]],
        system_msgs: Optional[List[Union[dict, Message]]] = None,
        stream: bool = True,
        temperature: Optional[float] = None,
        **kwargs,
    ) -> Tuple[str, Dict[str, float]]: ...

    """
    Sends messages to the language model and retrieves a response with top 5 logprobs, vllm version.

    Args:
        messages : A list of user or system messages, which can be dictionaries or Message objects.
        system_msgs: System messages providing context or guidance.
        stream : Whether to return the response in a streaming manner. Defaults to True.
        temperature : Controls the randomness of the model's output. Defaults to None.
        **kwargs: Additional optional parameters.

    Returns:
        str: The response from the model.
    """

    @abstractmethod
    async def ask_tool(
        self,
        messages: List[Union[dict, Message]],
        system_msgs: Optional[List[Union[dict, Message]]] = None,
        timeout: int = 60,
        tools: Optional[List[dict]] = None,
        tool_choice: TOOL_CHOICE_TYPE = "auto",
        temperature: Optional[float] = None,
        parallel_tool_calls: Optional[bool] = None,
        **kwargs,
    )-> str: ...


    """
    Sends messages to the language model and retrieves a response, using tools.

    Args:
        messages : A list of user or system messages, which can be dictionaries or Message objects.
        system_msgs : System messages providing context or guidance.
        timeout : The timeout time for tool invocation in seconds. Defaults to 60.
        tools : A list of available tools, each represented as a dictionary.
        tool_choice : The way to choose tools, which can be "auto", "none", or a list of tool names. Defaults to "auto".
        temperature : Controls the randomness of the model's output. Defaults to None.
        parallel_tool_calls : Whether to invoke tools in parallel. Defaults to None.
        **kwargs: Additional optional parameters.

    Returns:
        str: The response from the model.
    """

    async def ask_tool_stream(
        self,
        messages: List[Union[dict, Message]],
        system_msgs: Optional[List[Union[dict, Message]]] = None,
        timeout: int = 60,
        tools: Optional[List[dict]] = None,
        tool_choice: TOOL_CHOICE_TYPE = "auto",
        temperature: Optional[float] = None,
        parallel_tool_calls: Optional[bool] = None,
        *,
        handle: StreamHandle,
        collect_all_tool_calls: bool = False,
        **kwargs: Any,
    ) -> Any:
        """Streaming tool-calling completion; only ``OnlineLLM`` implements this."""
        raise NotImplementedError(
            "ask_tool_stream is implemented on OnlineLLM (and PooledLLM failover).",
        )

    async def ask_embedding(
        self,
        input: str,
        encoding_format: str = "float",
    )-> list:
        """
        Generates an embedding representation for the given text.

        Args:
            input : The input text to generate an embedding for.
            encoding_format : The format for encoding, which can be "float" or other supported formats. def. float

        Returns:
            list: The embedding representation of the text.

        Raises:
            NotImplementedError: If this method is not implemented.
        """
        raise NotImplementedError("ask_embedding is not implemented yet")

    def token_tracker(
            self,
            prompt_tokens,
            completion_tokens
    ):
        usage_record=None  # Initialize the return value
        if self.tracker:
            # Extract token usage from response
            input_tokens = int(prompt_tokens)
            output_tokens = int(completion_tokens)

            # Track token usage and calculate cost
            usage_record = self.usage_tracker.add_usage(
                self.model,
                input_tokens,
                output_tokens
            )

        return usage_record

    async def interrupt(self):
        """Interrupt the current generation process.

        .. deprecated::
            Use ``StreamHandle.interrupt()`` instead for per-call control.
            This instance-level method is kept for backward compatibility only.
        """
        self.interrupted = True
        if self.chunk_queue:
            while not self.chunk_queue.empty():
                try:
                    self.chunk_queue.get_nowait()
                except asyncio.QueueEmpty:
                    break
            await self.chunk_queue.put(None)
