"""Low-level database adapters for Qdrant and Neo4j."""

from .base import Neo4jStore as Neo4jStoreProtocol
from .base import QdrantStore as QdrantStoreProtocol
from .bootstrap import ensure_database_schema
from .collections import SkillVersionRepository
from .concurrency import (
    AsyncClientConcurrencyLimiter,
    DatabaseClientConcurrencyLimits,
    DatabaseClientKind,
)
from .errors import (
    MemoryDbConfigurationError,
    MemoryDbError,
    MemoryDbValidationError,
    MemoryNotFoundError,
)
from .filters import (
    FILTERABLE_ENTITY_FIELDS,
    FILTERABLE_MEMORY_FIELDS,
    build_filter,
    datetime_range,
    is_empty,
    is_null,
    match_any,
    match_except,
    match_text,
    match_value,
    number_range,
)
from .models import (
    AddRecordPoint,
    EntityNode,
    EntityPoint,
    GraphRelationship,
    MemoryNode,
    MemoryPoint,
    NodeRef,
    PayloadIndexSpec,
    QdrantCollectionSpec,
    QdrantRecord,
    QdrantSearchRecord,
    SchemaAddBufferPoint,
    SearchRecordPoint,
    SkillBlobPoint,
    SkillTracePendingPoint,
    SkillTraceSummaryPoint,
    SkillVersionPoint,
    SourceNode,
    SourcePoint,
    SparseVectorData,
)
from .neo4j import DEFAULT_SCHEMA_STATEMENTS, Neo4jStore
from .qdrant import QdrantStore
from .registry import (
    DatabaseClients,
    close_database_clients,
    get_database_clients,
    reset_database_clients,
    resolve_database_clients,
)
from .schema import (
    ADD_RECORD_COLLECTION,
    ENTITY_COLLECTION,
    MEMORY_COLLECTION,
    NEO4J_SCHEMA_STATEMENTS,
    SCHEMA_ADD_BUFFER_COLLECTION,
    SEARCH_RECORD_COLLECTION,
    SKILL_BLOB_COLLECTION,
    SKILL_TRACE_PENDING_COLLECTION,
    SKILL_TRACE_SUMMARY_COLLECTION,
    SKILL_VERSION_COLLECTION,
    SOURCE_COLLECTION,
)

__all__ = [
    "ADD_RECORD_COLLECTION",
    "AddRecordPoint",
    "AsyncClientConcurrencyLimiter",
    "DEFAULT_SCHEMA_STATEMENTS",
    "DatabaseClients",
    "DatabaseClientConcurrencyLimits",
    "DatabaseClientKind",
    "MemoryDbConfigurationError",
    "MemoryDbError",
    "MemoryDbValidationError",
    "MemoryNotFoundError",
    "EntityNode",
    "EntityPoint",
    "ENTITY_COLLECTION",
    "FILTERABLE_ENTITY_FIELDS",
    "FILTERABLE_MEMORY_FIELDS",
    "GraphRelationship",
    "MEMORY_COLLECTION",
    "MemoryNode",
    "MemoryPoint",
    "NEO4J_SCHEMA_STATEMENTS",
    "Neo4jStore",
    "Neo4jStoreProtocol",
    "NodeRef",
    "PayloadIndexSpec",
    "QdrantCollectionSpec",
    "QdrantRecord",
    "QdrantSearchRecord",
    "QdrantStore",
    "QdrantStoreProtocol",
    "SEARCH_RECORD_COLLECTION",
    "SCHEMA_ADD_BUFFER_COLLECTION",
    "SchemaAddBufferPoint",
    "SKILL_BLOB_COLLECTION",
    "SKILL_TRACE_PENDING_COLLECTION",
    "SKILL_TRACE_SUMMARY_COLLECTION",
    "SKILL_VERSION_COLLECTION",
    "SOURCE_COLLECTION",
    "SearchRecordPoint",
    "SkillBlobPoint",
    "SkillTracePendingPoint",
    "SkillTraceSummaryPoint",
    "SkillVersionPoint",
    "SkillVersionRepository",
    "SourceNode",
    "SourcePoint",
    "SparseVectorData",
    "build_filter",
    "datetime_range",
    "ensure_database_schema",
    "get_database_clients",
    "is_empty",
    "is_null",
    "match_any",
    "match_except",
    "match_text",
    "match_value",
    "number_range",
    "close_database_clients",
    "reset_database_clients",
    "resolve_database_clients",
]
