version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_checkout:
      - cd EvoFabric

sphinx:
  configuration: EvoFabric/docs/source/conf.py

python:
  install:
    - method: pip
      path: EvoFabric