version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: EvoFabric/docs/source/conf.py

python:
  install:
    - requirements: EvoFabric/docs/requirements.txt
    - method: pip
      path: EvoFabric